// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

package com.mrmq.poker.common.proto;

public final class Heartbeat {
  private Heartbeat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeartbeatMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string serverTime = 1;
    /**
     * <code>optional string serverTime = 1;</code>
     */
    boolean hasServerTime();
    /**
     * <code>optional string serverTime = 1;</code>
     */
    java.lang.String getServerTime();
    /**
     * <code>optional string serverTime = 1;</code>
     */
    com.google.protobuf.ByteString
        getServerTimeBytes();

    // optional int32 onlineUsers = 2;
    /**
     * <code>optional int32 onlineUsers = 2;</code>
     */
    boolean hasOnlineUsers();
    /**
     * <code>optional int32 onlineUsers = 2;</code>
     */
    int getOnlineUsers();
  }
  /**
   * Protobuf type {@code HeartbeatMessage}
   */
  public static final class HeartbeatMessage extends
      com.google.protobuf.GeneratedMessage
      implements HeartbeatMessageOrBuilder {
    // Use HeartbeatMessage.newBuilder() to construct.
    private HeartbeatMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeartbeatMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeartbeatMessage defaultInstance;
    public static HeartbeatMessage getDefaultInstance() {
      return defaultInstance;
    }

    public HeartbeatMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeartbeatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serverTime_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              onlineUsers_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mrmq.poker.common.proto.Heartbeat.internal_static_HeartbeatMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mrmq.poker.common.proto.Heartbeat.internal_static_HeartbeatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage.class, com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<HeartbeatMessage> PARSER =
        new com.google.protobuf.AbstractParser<HeartbeatMessage>() {
      public HeartbeatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartbeatMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HeartbeatMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string serverTime = 1;
    public static final int SERVERTIME_FIELD_NUMBER = 1;
    private java.lang.Object serverTime_;
    /**
     * <code>optional string serverTime = 1;</code>
     */
    public boolean hasServerTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string serverTime = 1;</code>
     */
    public java.lang.String getServerTime() {
      java.lang.Object ref = serverTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string serverTime = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServerTimeBytes() {
      java.lang.Object ref = serverTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 onlineUsers = 2;
    public static final int ONLINEUSERS_FIELD_NUMBER = 2;
    private int onlineUsers_;
    /**
     * <code>optional int32 onlineUsers = 2;</code>
     */
    public boolean hasOnlineUsers() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 onlineUsers = 2;</code>
     */
    public int getOnlineUsers() {
      return onlineUsers_;
    }

    private void initFields() {
      serverTime_ = "";
      onlineUsers_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServerTimeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, onlineUsers_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServerTimeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, onlineUsers_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartbeatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mrmq.poker.common.proto.Heartbeat.internal_static_HeartbeatMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mrmq.poker.common.proto.Heartbeat.internal_static_HeartbeatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage.class, com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage.Builder.class);
      }

      // Construct using com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        onlineUsers_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mrmq.poker.common.proto.Heartbeat.internal_static_HeartbeatMessage_descriptor;
      }

      public com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage getDefaultInstanceForType() {
        return com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage.getDefaultInstance();
      }

      public com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage build() {
        com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage buildPartial() {
        com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage result = new com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverTime_ = serverTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.onlineUsers_ = onlineUsers_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage) {
          return mergeFrom((com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage other) {
        if (other == com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage.getDefaultInstance()) return this;
        if (other.hasServerTime()) {
          bitField0_ |= 0x00000001;
          serverTime_ = other.serverTime_;
          onChanged();
        }
        if (other.hasOnlineUsers()) {
          setOnlineUsers(other.getOnlineUsers());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mrmq.poker.common.proto.Heartbeat.HeartbeatMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string serverTime = 1;
      private java.lang.Object serverTime_ = "";
      /**
       * <code>optional string serverTime = 1;</code>
       */
      public boolean hasServerTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string serverTime = 1;</code>
       */
      public java.lang.String getServerTime() {
        java.lang.Object ref = serverTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serverTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serverTime = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServerTimeBytes() {
        java.lang.Object ref = serverTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serverTime = 1;</code>
       */
      public Builder setServerTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverTime = 1;</code>
       */
      public Builder clearServerTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverTime_ = getDefaultInstance().getServerTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverTime = 1;</code>
       */
      public Builder setServerTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverTime_ = value;
        onChanged();
        return this;
      }

      // optional int32 onlineUsers = 2;
      private int onlineUsers_ ;
      /**
       * <code>optional int32 onlineUsers = 2;</code>
       */
      public boolean hasOnlineUsers() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 onlineUsers = 2;</code>
       */
      public int getOnlineUsers() {
        return onlineUsers_;
      }
      /**
       * <code>optional int32 onlineUsers = 2;</code>
       */
      public Builder setOnlineUsers(int value) {
        bitField0_ |= 0x00000002;
        onlineUsers_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 onlineUsers = 2;</code>
       */
      public Builder clearOnlineUsers() {
        bitField0_ = (bitField0_ & ~0x00000002);
        onlineUsers_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HeartbeatMessage)
    }

    static {
      defaultInstance = new HeartbeatMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HeartbeatMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartbeatMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HeartbeatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017heartbeat.proto\032\trpc.proto\";\n\020Heartbea" +
      "tMessage\022\022\n\nserverTime\030\001 \001(\t\022\023\n\013onlineUs" +
      "ers\030\002 \001(\0052?\n\rSearchService\022.\n\006Search\022\021.H" +
      "eartbeatMessage\032\021.HeartbeatMessageB(\n\033co" +
      "m.mrmq.poker.common.protoB\tHeartbeat"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_HeartbeatMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_HeartbeatMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HeartbeatMessage_descriptor,
              new java.lang.String[] { "ServerTime", "OnlineUsers", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.mrmq.poker.common.proto.Rpc.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
