// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manager_model.proto

package com.mrmq.poker.common.proto;

public final class ManagerModelProto {
  private ManagerModelProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code UserType}
   */
  public enum UserType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ALL = 1;</code>
     */
    ALL(0, 1),
    /**
     * <code>BOT = 2;</code>
     */
    BOT(1, 2),
    /**
     * <code>PLAYER = 3;</code>
     */
    PLAYER(2, 3),
    ;

    /**
     * <code>ALL = 1;</code>
     */
    public static final int ALL_VALUE = 1;
    /**
     * <code>BOT = 2;</code>
     */
    public static final int BOT_VALUE = 2;
    /**
     * <code>PLAYER = 3;</code>
     */
    public static final int PLAYER_VALUE = 3;


    public final int getNumber() { return value; }

    public static UserType valueOf(int value) {
      switch (value) {
        case 1: return ALL;
        case 2: return BOT;
        case 3: return PLAYER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<UserType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserType>() {
            public UserType findValueByNumber(int number) {
              return UserType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.mrmq.poker.common.proto.ManagerModelProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final UserType[] VALUES = values();

    public static UserType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private UserType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:UserType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023manager_model.proto*(\n\010UserType\022\007\n\003ALL" +
      "\020\001\022\007\n\003BOT\020\002\022\n\n\006PLAYER\020\003B0\n\033com.mrmq.poke" +
      "r.common.protoB\021ManagerModelProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
