// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manager_service.proto

package com.mrmq.poker.common.proto;

public final class ManagerServiceProto {
  private ManagerServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UsersRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .UserType userType = 1;
    /**
     * <code>required .UserType userType = 1;</code>
     */
    boolean hasUserType();
    /**
     * <code>required .UserType userType = 1;</code>
     */
    com.mrmq.poker.common.proto.ManagerModelProto.UserType getUserType();
  }
  /**
   * Protobuf type {@code UsersRequest}
   */
  public static final class UsersRequest extends
      com.google.protobuf.GeneratedMessage
      implements UsersRequestOrBuilder {
    // Use UsersRequest.newBuilder() to construct.
    private UsersRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UsersRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UsersRequest defaultInstance;
    public static UsersRequest getDefaultInstance() {
      return defaultInstance;
    }

    public UsersRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UsersRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.mrmq.poker.common.proto.ManagerModelProto.UserType value = com.mrmq.poker.common.proto.ManagerModelProto.UserType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                userType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mrmq.poker.common.proto.ManagerServiceProto.internal_static_UsersRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mrmq.poker.common.proto.ManagerServiceProto.internal_static_UsersRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest.class, com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<UsersRequest> PARSER =
        new com.google.protobuf.AbstractParser<UsersRequest>() {
      public UsersRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UsersRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UsersRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .UserType userType = 1;
    public static final int USERTYPE_FIELD_NUMBER = 1;
    private com.mrmq.poker.common.proto.ManagerModelProto.UserType userType_;
    /**
     * <code>required .UserType userType = 1;</code>
     */
    public boolean hasUserType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .UserType userType = 1;</code>
     */
    public com.mrmq.poker.common.proto.ManagerModelProto.UserType getUserType() {
      return userType_;
    }

    private void initFields() {
      userType_ = com.mrmq.poker.common.proto.ManagerModelProto.UserType.ALL;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, userType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, userType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UsersRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mrmq.poker.common.proto.ManagerServiceProto.internal_static_UsersRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mrmq.poker.common.proto.ManagerServiceProto.internal_static_UsersRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest.class, com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest.Builder.class);
      }

      // Construct using com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userType_ = com.mrmq.poker.common.proto.ManagerModelProto.UserType.ALL;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mrmq.poker.common.proto.ManagerServiceProto.internal_static_UsersRequest_descriptor;
      }

      public com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest getDefaultInstanceForType() {
        return com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest.getDefaultInstance();
      }

      public com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest build() {
        com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest buildPartial() {
        com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest result = new com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userType_ = userType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest) {
          return mergeFrom((com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest other) {
        if (other == com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest.getDefaultInstance()) return this;
        if (other.hasUserType()) {
          setUserType(other.getUserType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mrmq.poker.common.proto.ManagerServiceProto.UsersRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .UserType userType = 1;
      private com.mrmq.poker.common.proto.ManagerModelProto.UserType userType_ = com.mrmq.poker.common.proto.ManagerModelProto.UserType.ALL;
      /**
       * <code>required .UserType userType = 1;</code>
       */
      public boolean hasUserType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .UserType userType = 1;</code>
       */
      public com.mrmq.poker.common.proto.ManagerModelProto.UserType getUserType() {
        return userType_;
      }
      /**
       * <code>required .UserType userType = 1;</code>
       */
      public Builder setUserType(com.mrmq.poker.common.proto.ManagerModelProto.UserType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        userType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .UserType userType = 1;</code>
       */
      public Builder clearUserType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userType_ = com.mrmq.poker.common.proto.ManagerModelProto.UserType.ALL;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:UsersRequest)
    }

    static {
      defaultInstance = new UsersRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:UsersRequest)
  }

  public interface UsersResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .UserType userType = 1;
    /**
     * <code>required .UserType userType = 1;</code>
     */
    boolean hasUserType();
    /**
     * <code>required .UserType userType = 1;</code>
     */
    com.mrmq.poker.common.proto.ManagerModelProto.UserType getUserType();

    // repeated .User users = 5;
    /**
     * <code>repeated .User users = 5;</code>
     */
    java.util.List<com.mrmq.poker.common.proto.AdminModelProto.User> 
        getUsersList();
    /**
     * <code>repeated .User users = 5;</code>
     */
    com.mrmq.poker.common.proto.AdminModelProto.User getUsers(int index);
    /**
     * <code>repeated .User users = 5;</code>
     */
    int getUsersCount();
    /**
     * <code>repeated .User users = 5;</code>
     */
    java.util.List<? extends com.mrmq.poker.common.proto.AdminModelProto.UserOrBuilder> 
        getUsersOrBuilderList();
    /**
     * <code>repeated .User users = 5;</code>
     */
    com.mrmq.poker.common.proto.AdminModelProto.UserOrBuilder getUsersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code UsersResponse}
   */
  public static final class UsersResponse extends
      com.google.protobuf.GeneratedMessage
      implements UsersResponseOrBuilder {
    // Use UsersResponse.newBuilder() to construct.
    private UsersResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UsersResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UsersResponse defaultInstance;
    public static UsersResponse getDefaultInstance() {
      return defaultInstance;
    }

    public UsersResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UsersResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.mrmq.poker.common.proto.ManagerModelProto.UserType value = com.mrmq.poker.common.proto.ManagerModelProto.UserType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                userType_ = value;
              }
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                users_ = new java.util.ArrayList<com.mrmq.poker.common.proto.AdminModelProto.User>();
                mutable_bitField0_ |= 0x00000002;
              }
              users_.add(input.readMessage(com.mrmq.poker.common.proto.AdminModelProto.User.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          users_ = java.util.Collections.unmodifiableList(users_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mrmq.poker.common.proto.ManagerServiceProto.internal_static_UsersResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mrmq.poker.common.proto.ManagerServiceProto.internal_static_UsersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse.class, com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<UsersResponse> PARSER =
        new com.google.protobuf.AbstractParser<UsersResponse>() {
      public UsersResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UsersResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UsersResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .UserType userType = 1;
    public static final int USERTYPE_FIELD_NUMBER = 1;
    private com.mrmq.poker.common.proto.ManagerModelProto.UserType userType_;
    /**
     * <code>required .UserType userType = 1;</code>
     */
    public boolean hasUserType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .UserType userType = 1;</code>
     */
    public com.mrmq.poker.common.proto.ManagerModelProto.UserType getUserType() {
      return userType_;
    }

    // repeated .User users = 5;
    public static final int USERS_FIELD_NUMBER = 5;
    private java.util.List<com.mrmq.poker.common.proto.AdminModelProto.User> users_;
    /**
     * <code>repeated .User users = 5;</code>
     */
    public java.util.List<com.mrmq.poker.common.proto.AdminModelProto.User> getUsersList() {
      return users_;
    }
    /**
     * <code>repeated .User users = 5;</code>
     */
    public java.util.List<? extends com.mrmq.poker.common.proto.AdminModelProto.UserOrBuilder> 
        getUsersOrBuilderList() {
      return users_;
    }
    /**
     * <code>repeated .User users = 5;</code>
     */
    public int getUsersCount() {
      return users_.size();
    }
    /**
     * <code>repeated .User users = 5;</code>
     */
    public com.mrmq.poker.common.proto.AdminModelProto.User getUsers(int index) {
      return users_.get(index);
    }
    /**
     * <code>repeated .User users = 5;</code>
     */
    public com.mrmq.poker.common.proto.AdminModelProto.UserOrBuilder getUsersOrBuilder(
        int index) {
      return users_.get(index);
    }

    private void initFields() {
      userType_ = com.mrmq.poker.common.proto.ManagerModelProto.UserType.ALL;
      users_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getUsersCount(); i++) {
        if (!getUsers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, userType_.getNumber());
      }
      for (int i = 0; i < users_.size(); i++) {
        output.writeMessage(5, users_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, userType_.getNumber());
      }
      for (int i = 0; i < users_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, users_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UsersResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mrmq.poker.common.proto.ManagerServiceProto.internal_static_UsersResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mrmq.poker.common.proto.ManagerServiceProto.internal_static_UsersResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse.class, com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse.Builder.class);
      }

      // Construct using com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUsersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userType_ = com.mrmq.poker.common.proto.ManagerModelProto.UserType.ALL;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          usersBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mrmq.poker.common.proto.ManagerServiceProto.internal_static_UsersResponse_descriptor;
      }

      public com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse getDefaultInstanceForType() {
        return com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse.getDefaultInstance();
      }

      public com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse build() {
        com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse buildPartial() {
        com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse result = new com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userType_ = userType_;
        if (usersBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            users_ = java.util.Collections.unmodifiableList(users_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.users_ = users_;
        } else {
          result.users_ = usersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse) {
          return mergeFrom((com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse other) {
        if (other == com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse.getDefaultInstance()) return this;
        if (other.hasUserType()) {
          setUserType(other.getUserType());
        }
        if (usersBuilder_ == null) {
          if (!other.users_.isEmpty()) {
            if (users_.isEmpty()) {
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureUsersIsMutable();
              users_.addAll(other.users_);
            }
            onChanged();
          }
        } else {
          if (!other.users_.isEmpty()) {
            if (usersBuilder_.isEmpty()) {
              usersBuilder_.dispose();
              usersBuilder_ = null;
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000002);
              usersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUsersFieldBuilder() : null;
            } else {
              usersBuilder_.addAllMessages(other.users_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserType()) {
          
          return false;
        }
        for (int i = 0; i < getUsersCount(); i++) {
          if (!getUsers(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mrmq.poker.common.proto.ManagerServiceProto.UsersResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .UserType userType = 1;
      private com.mrmq.poker.common.proto.ManagerModelProto.UserType userType_ = com.mrmq.poker.common.proto.ManagerModelProto.UserType.ALL;
      /**
       * <code>required .UserType userType = 1;</code>
       */
      public boolean hasUserType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .UserType userType = 1;</code>
       */
      public com.mrmq.poker.common.proto.ManagerModelProto.UserType getUserType() {
        return userType_;
      }
      /**
       * <code>required .UserType userType = 1;</code>
       */
      public Builder setUserType(com.mrmq.poker.common.proto.ManagerModelProto.UserType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        userType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .UserType userType = 1;</code>
       */
      public Builder clearUserType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userType_ = com.mrmq.poker.common.proto.ManagerModelProto.UserType.ALL;
        onChanged();
        return this;
      }

      // repeated .User users = 5;
      private java.util.List<com.mrmq.poker.common.proto.AdminModelProto.User> users_ =
        java.util.Collections.emptyList();
      private void ensureUsersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          users_ = new java.util.ArrayList<com.mrmq.poker.common.proto.AdminModelProto.User>(users_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.mrmq.poker.common.proto.AdminModelProto.User, com.mrmq.poker.common.proto.AdminModelProto.User.Builder, com.mrmq.poker.common.proto.AdminModelProto.UserOrBuilder> usersBuilder_;

      /**
       * <code>repeated .User users = 5;</code>
       */
      public java.util.List<com.mrmq.poker.common.proto.AdminModelProto.User> getUsersList() {
        if (usersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(users_);
        } else {
          return usersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public int getUsersCount() {
        if (usersBuilder_ == null) {
          return users_.size();
        } else {
          return usersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public com.mrmq.poker.common.proto.AdminModelProto.User getUsers(int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);
        } else {
          return usersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public Builder setUsers(
          int index, com.mrmq.poker.common.proto.AdminModelProto.User value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.set(index, value);
          onChanged();
        } else {
          usersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public Builder setUsers(
          int index, com.mrmq.poker.common.proto.AdminModelProto.User.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.set(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public Builder addUsers(com.mrmq.poker.common.proto.AdminModelProto.User value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(value);
          onChanged();
        } else {
          usersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public Builder addUsers(
          int index, com.mrmq.poker.common.proto.AdminModelProto.User value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(index, value);
          onChanged();
        } else {
          usersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public Builder addUsers(
          com.mrmq.poker.common.proto.AdminModelProto.User.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public Builder addUsers(
          int index, com.mrmq.poker.common.proto.AdminModelProto.User.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public Builder addAllUsers(
          java.lang.Iterable<? extends com.mrmq.poker.common.proto.AdminModelProto.User> values) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          super.addAll(values, users_);
          onChanged();
        } else {
          usersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public Builder clearUsers() {
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          usersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public Builder removeUsers(int index) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.remove(index);
          onChanged();
        } else {
          usersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public com.mrmq.poker.common.proto.AdminModelProto.User.Builder getUsersBuilder(
          int index) {
        return getUsersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public com.mrmq.poker.common.proto.AdminModelProto.UserOrBuilder getUsersOrBuilder(
          int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);  } else {
          return usersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public java.util.List<? extends com.mrmq.poker.common.proto.AdminModelProto.UserOrBuilder> 
           getUsersOrBuilderList() {
        if (usersBuilder_ != null) {
          return usersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(users_);
        }
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public com.mrmq.poker.common.proto.AdminModelProto.User.Builder addUsersBuilder() {
        return getUsersFieldBuilder().addBuilder(
            com.mrmq.poker.common.proto.AdminModelProto.User.getDefaultInstance());
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public com.mrmq.poker.common.proto.AdminModelProto.User.Builder addUsersBuilder(
          int index) {
        return getUsersFieldBuilder().addBuilder(
            index, com.mrmq.poker.common.proto.AdminModelProto.User.getDefaultInstance());
      }
      /**
       * <code>repeated .User users = 5;</code>
       */
      public java.util.List<com.mrmq.poker.common.proto.AdminModelProto.User.Builder> 
           getUsersBuilderList() {
        return getUsersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mrmq.poker.common.proto.AdminModelProto.User, com.mrmq.poker.common.proto.AdminModelProto.User.Builder, com.mrmq.poker.common.proto.AdminModelProto.UserOrBuilder> 
          getUsersFieldBuilder() {
        if (usersBuilder_ == null) {
          usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.mrmq.poker.common.proto.AdminModelProto.User, com.mrmq.poker.common.proto.AdminModelProto.User.Builder, com.mrmq.poker.common.proto.AdminModelProto.UserOrBuilder>(
                  users_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          users_ = null;
        }
        return usersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:UsersResponse)
    }

    static {
      defaultInstance = new UsersResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:UsersResponse)
  }

  public interface JoinTableRequestEventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .Table table = 1;
    /**
     * <code>required .Table table = 1;</code>
     */
    boolean hasTable();
    /**
     * <code>required .Table table = 1;</code>
     */
    com.mrmq.poker.common.proto.PokerModelProto.Table getTable();
    /**
     * <code>required .Table table = 1;</code>
     */
    com.mrmq.poker.common.proto.PokerModelProto.TableOrBuilder getTableOrBuilder();
  }
  /**
   * Protobuf type {@code JoinTableRequestEvent}
   *
   * <pre>
   *User Join/Reconnect to game
   * </pre>
   */
  public static final class JoinTableRequestEvent extends
      com.google.protobuf.GeneratedMessage
      implements JoinTableRequestEventOrBuilder {
    // Use JoinTableRequestEvent.newBuilder() to construct.
    private JoinTableRequestEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JoinTableRequestEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JoinTableRequestEvent defaultInstance;
    public static JoinTableRequestEvent getDefaultInstance() {
      return defaultInstance;
    }

    public JoinTableRequestEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JoinTableRequestEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.mrmq.poker.common.proto.PokerModelProto.Table.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = table_.toBuilder();
              }
              table_ = input.readMessage(com.mrmq.poker.common.proto.PokerModelProto.Table.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(table_);
                table_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mrmq.poker.common.proto.ManagerServiceProto.internal_static_JoinTableRequestEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mrmq.poker.common.proto.ManagerServiceProto.internal_static_JoinTableRequestEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent.class, com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<JoinTableRequestEvent> PARSER =
        new com.google.protobuf.AbstractParser<JoinTableRequestEvent>() {
      public JoinTableRequestEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JoinTableRequestEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JoinTableRequestEvent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .Table table = 1;
    public static final int TABLE_FIELD_NUMBER = 1;
    private com.mrmq.poker.common.proto.PokerModelProto.Table table_;
    /**
     * <code>required .Table table = 1;</code>
     */
    public boolean hasTable() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Table table = 1;</code>
     */
    public com.mrmq.poker.common.proto.PokerModelProto.Table getTable() {
      return table_;
    }
    /**
     * <code>required .Table table = 1;</code>
     */
    public com.mrmq.poker.common.proto.PokerModelProto.TableOrBuilder getTableOrBuilder() {
      return table_;
    }

    private void initFields() {
      table_ = com.mrmq.poker.common.proto.PokerModelProto.Table.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTable()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTable().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, table_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, table_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JoinTableRequestEvent}
     *
     * <pre>
     *User Join/Reconnect to game
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mrmq.poker.common.proto.ManagerServiceProto.internal_static_JoinTableRequestEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mrmq.poker.common.proto.ManagerServiceProto.internal_static_JoinTableRequestEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent.class, com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent.Builder.class);
      }

      // Construct using com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTableFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (tableBuilder_ == null) {
          table_ = com.mrmq.poker.common.proto.PokerModelProto.Table.getDefaultInstance();
        } else {
          tableBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mrmq.poker.common.proto.ManagerServiceProto.internal_static_JoinTableRequestEvent_descriptor;
      }

      public com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent getDefaultInstanceForType() {
        return com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent.getDefaultInstance();
      }

      public com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent build() {
        com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent buildPartial() {
        com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent result = new com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (tableBuilder_ == null) {
          result.table_ = table_;
        } else {
          result.table_ = tableBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent) {
          return mergeFrom((com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent other) {
        if (other == com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent.getDefaultInstance()) return this;
        if (other.hasTable()) {
          mergeTable(other.getTable());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTable()) {
          
          return false;
        }
        if (!getTable().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mrmq.poker.common.proto.ManagerServiceProto.JoinTableRequestEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .Table table = 1;
      private com.mrmq.poker.common.proto.PokerModelProto.Table table_ = com.mrmq.poker.common.proto.PokerModelProto.Table.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.mrmq.poker.common.proto.PokerModelProto.Table, com.mrmq.poker.common.proto.PokerModelProto.Table.Builder, com.mrmq.poker.common.proto.PokerModelProto.TableOrBuilder> tableBuilder_;
      /**
       * <code>required .Table table = 1;</code>
       */
      public boolean hasTable() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Table table = 1;</code>
       */
      public com.mrmq.poker.common.proto.PokerModelProto.Table getTable() {
        if (tableBuilder_ == null) {
          return table_;
        } else {
          return tableBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Table table = 1;</code>
       */
      public Builder setTable(com.mrmq.poker.common.proto.PokerModelProto.Table value) {
        if (tableBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          table_ = value;
          onChanged();
        } else {
          tableBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Table table = 1;</code>
       */
      public Builder setTable(
          com.mrmq.poker.common.proto.PokerModelProto.Table.Builder builderForValue) {
        if (tableBuilder_ == null) {
          table_ = builderForValue.build();
          onChanged();
        } else {
          tableBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Table table = 1;</code>
       */
      public Builder mergeTable(com.mrmq.poker.common.proto.PokerModelProto.Table value) {
        if (tableBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              table_ != com.mrmq.poker.common.proto.PokerModelProto.Table.getDefaultInstance()) {
            table_ =
              com.mrmq.poker.common.proto.PokerModelProto.Table.newBuilder(table_).mergeFrom(value).buildPartial();
          } else {
            table_ = value;
          }
          onChanged();
        } else {
          tableBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Table table = 1;</code>
       */
      public Builder clearTable() {
        if (tableBuilder_ == null) {
          table_ = com.mrmq.poker.common.proto.PokerModelProto.Table.getDefaultInstance();
          onChanged();
        } else {
          tableBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .Table table = 1;</code>
       */
      public com.mrmq.poker.common.proto.PokerModelProto.Table.Builder getTableBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTableFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Table table = 1;</code>
       */
      public com.mrmq.poker.common.proto.PokerModelProto.TableOrBuilder getTableOrBuilder() {
        if (tableBuilder_ != null) {
          return tableBuilder_.getMessageOrBuilder();
        } else {
          return table_;
        }
      }
      /**
       * <code>required .Table table = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.mrmq.poker.common.proto.PokerModelProto.Table, com.mrmq.poker.common.proto.PokerModelProto.Table.Builder, com.mrmq.poker.common.proto.PokerModelProto.TableOrBuilder> 
          getTableFieldBuilder() {
        if (tableBuilder_ == null) {
          tableBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.mrmq.poker.common.proto.PokerModelProto.Table, com.mrmq.poker.common.proto.PokerModelProto.Table.Builder, com.mrmq.poker.common.proto.PokerModelProto.TableOrBuilder>(
                  table_,
                  getParentForChildren(),
                  isClean());
          table_ = null;
        }
        return tableBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:JoinTableRequestEvent)
    }

    static {
      defaultInstance = new JoinTableRequestEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:JoinTableRequestEvent)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UsersRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UsersRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UsersResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UsersResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_JoinTableRequestEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_JoinTableRequestEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025manager_service.proto\032\021admin_model.pro" +
      "to\032\021poker_model.proto\032\023manager_model.pro" +
      "to\"+\n\014UsersRequest\022\033\n\010userType\030\001 \002(\0162\t.U" +
      "serType\"B\n\rUsersResponse\022\033\n\010userType\030\001 \002" +
      "(\0162\t.UserType\022\024\n\005users\030\005 \003(\0132\005.User\".\n\025J" +
      "oinTableRequestEvent\022\025\n\005table\030\001 \002(\0132\006.Ta" +
      "bleB2\n\033com.mrmq.poker.common.protoB\023Mana" +
      "gerServiceProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_UsersRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_UsersRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UsersRequest_descriptor,
              new java.lang.String[] { "UserType", });
          internal_static_UsersResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_UsersResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UsersResponse_descriptor,
              new java.lang.String[] { "UserType", "Users", });
          internal_static_JoinTableRequestEvent_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_JoinTableRequestEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_JoinTableRequestEvent_descriptor,
              new java.lang.String[] { "Table", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.mrmq.poker.common.proto.AdminModelProto.getDescriptor(),
          com.mrmq.poker.common.proto.PokerModelProto.getDescriptor(),
          com.mrmq.poker.common.proto.ManagerModelProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
