// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.mrmq.poker.common.proto;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RpcMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 id = 1;
    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    // required string version = 2;
    /**
     * <code>required string version = 2;</code>
     */
    boolean hasVersion();
    /**
     * <code>required string version = 2;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>required string version = 2;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    // required string service = 3;
    /**
     * <code>required string service = 3;</code>
     */
    boolean hasService();
    /**
     * <code>required string service = 3;</code>
     */
    java.lang.String getService();
    /**
     * <code>required string service = 3;</code>
     */
    com.google.protobuf.ByteString
        getServiceBytes();

    // optional int64 source_id = 4;
    /**
     * <code>optional int64 source_id = 4;</code>
     */
    boolean hasSourceId();
    /**
     * <code>optional int64 source_id = 4;</code>
     */
    long getSourceId();

    // optional bytes payloadData = 5;
    /**
     * <code>optional bytes payloadData = 5;</code>
     */
    boolean hasPayloadData();
    /**
     * <code>optional bytes payloadData = 5;</code>
     */
    com.google.protobuf.ByteString getPayloadData();

    // optional string payloadClass = 6;
    /**
     * <code>optional string payloadClass = 6;</code>
     */
    boolean hasPayloadClass();
    /**
     * <code>optional string payloadClass = 6;</code>
     */
    java.lang.String getPayloadClass();
    /**
     * <code>optional string payloadClass = 6;</code>
     */
    com.google.protobuf.ByteString
        getPayloadClassBytes();

    // optional .RpcMessage.Result result = 7;
    /**
     * <code>optional .RpcMessage.Result result = 7;</code>
     */
    boolean hasResult();
    /**
     * <code>optional .RpcMessage.Result result = 7;</code>
     */
    com.mrmq.poker.common.proto.Rpc.RpcMessage.Result getResult();

    // optional string msgCode = 8;
    /**
     * <code>optional string msgCode = 8;</code>
     */
    boolean hasMsgCode();
    /**
     * <code>optional string msgCode = 8;</code>
     */
    java.lang.String getMsgCode();
    /**
     * <code>optional string msgCode = 8;</code>
     */
    com.google.protobuf.ByteString
        getMsgCodeBytes();

    // optional string message = 9;
    /**
     * <code>optional string message = 9;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 9;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 9;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code RpcMessage}
   */
  public static final class RpcMessage extends
      com.google.protobuf.GeneratedMessage
      implements RpcMessageOrBuilder {
    // Use RpcMessage.newBuilder() to construct.
    private RpcMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcMessage defaultInstance;
    public static RpcMessage getDefaultInstance() {
      return defaultInstance;
    }

    public RpcMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RpcMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              version_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              service_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sourceId_ = input.readInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              payloadData_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              payloadClass_ = input.readBytes();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              com.mrmq.poker.common.proto.Rpc.RpcMessage.Result value = com.mrmq.poker.common.proto.Rpc.RpcMessage.Result.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                result_ = value;
              }
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              msgCode_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              message_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mrmq.poker.common.proto.Rpc.internal_static_RpcMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mrmq.poker.common.proto.Rpc.internal_static_RpcMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mrmq.poker.common.proto.Rpc.RpcMessage.class, com.mrmq.poker.common.proto.Rpc.RpcMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcMessage> PARSER =
        new com.google.protobuf.AbstractParser<RpcMessage>() {
      public RpcMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code RpcMessage.Result}
     */
    public enum Result
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0, 0),
      /**
       * <code>FAIL = 1;</code>
       */
      FAIL(1, 1),
      /**
       * <code>INVALID_VERSION = 2;</code>
       */
      INVALID_VERSION(2, 2),
      /**
       * <code>INVALID_SERVICE = 3;</code>
       */
      INVALID_SERVICE(3, 3),
      /**
       * <code>INVALID_PAYLOAD = 4;</code>
       */
      INVALID_PAYLOAD(4, 4),
      /**
       * <code>NOT_AUTHENTICATED = 5;</code>
       */
      NOT_AUTHENTICATED(5, 5),
      /**
       * <code>SERVICE_UNAVAILABLE = 6;</code>
       */
      SERVICE_UNAVAILABLE(6, 6),
      /**
       * <code>SERVICE_MAINTAIN = 8;</code>
       */
      SERVICE_MAINTAIN(7, 8),
      /**
       * <code>INTERNAL_ERROR = 99;</code>
       */
      INTERNAL_ERROR(8, 99),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <code>FAIL = 1;</code>
       */
      public static final int FAIL_VALUE = 1;
      /**
       * <code>INVALID_VERSION = 2;</code>
       */
      public static final int INVALID_VERSION_VALUE = 2;
      /**
       * <code>INVALID_SERVICE = 3;</code>
       */
      public static final int INVALID_SERVICE_VALUE = 3;
      /**
       * <code>INVALID_PAYLOAD = 4;</code>
       */
      public static final int INVALID_PAYLOAD_VALUE = 4;
      /**
       * <code>NOT_AUTHENTICATED = 5;</code>
       */
      public static final int NOT_AUTHENTICATED_VALUE = 5;
      /**
       * <code>SERVICE_UNAVAILABLE = 6;</code>
       */
      public static final int SERVICE_UNAVAILABLE_VALUE = 6;
      /**
       * <code>SERVICE_MAINTAIN = 8;</code>
       */
      public static final int SERVICE_MAINTAIN_VALUE = 8;
      /**
       * <code>INTERNAL_ERROR = 99;</code>
       */
      public static final int INTERNAL_ERROR_VALUE = 99;


      public final int getNumber() { return value; }

      public static Result valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return FAIL;
          case 2: return INVALID_VERSION;
          case 3: return INVALID_SERVICE;
          case 4: return INVALID_PAYLOAD;
          case 5: return NOT_AUTHENTICATED;
          case 6: return SERVICE_UNAVAILABLE;
          case 8: return SERVICE_MAINTAIN;
          case 99: return INTERNAL_ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Result>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Result>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Result>() {
              public Result findValueByNumber(int number) {
                return Result.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.mrmq.poker.common.proto.Rpc.RpcMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Result[] VALUES = values();

      public static Result valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Result(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RpcMessage.Result)
    }

    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // required string version = 2;
    public static final int VERSION_FIELD_NUMBER = 2;
    private java.lang.Object version_;
    /**
     * <code>required string version = 2;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string version = 2;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string version = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string service = 3;
    public static final int SERVICE_FIELD_NUMBER = 3;
    private java.lang.Object service_;
    /**
     * <code>required string service = 3;</code>
     */
    public boolean hasService() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string service = 3;</code>
     */
    public java.lang.String getService() {
      java.lang.Object ref = service_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          service_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string service = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServiceBytes() {
      java.lang.Object ref = service_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        service_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 source_id = 4;
    public static final int SOURCE_ID_FIELD_NUMBER = 4;
    private long sourceId_;
    /**
     * <code>optional int64 source_id = 4;</code>
     */
    public boolean hasSourceId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 source_id = 4;</code>
     */
    public long getSourceId() {
      return sourceId_;
    }

    // optional bytes payloadData = 5;
    public static final int PAYLOADDATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString payloadData_;
    /**
     * <code>optional bytes payloadData = 5;</code>
     */
    public boolean hasPayloadData() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes payloadData = 5;</code>
     */
    public com.google.protobuf.ByteString getPayloadData() {
      return payloadData_;
    }

    // optional string payloadClass = 6;
    public static final int PAYLOADCLASS_FIELD_NUMBER = 6;
    private java.lang.Object payloadClass_;
    /**
     * <code>optional string payloadClass = 6;</code>
     */
    public boolean hasPayloadClass() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string payloadClass = 6;</code>
     */
    public java.lang.String getPayloadClass() {
      java.lang.Object ref = payloadClass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          payloadClass_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string payloadClass = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPayloadClassBytes() {
      java.lang.Object ref = payloadClass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payloadClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .RpcMessage.Result result = 7;
    public static final int RESULT_FIELD_NUMBER = 7;
    private com.mrmq.poker.common.proto.Rpc.RpcMessage.Result result_;
    /**
     * <code>optional .RpcMessage.Result result = 7;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .RpcMessage.Result result = 7;</code>
     */
    public com.mrmq.poker.common.proto.Rpc.RpcMessage.Result getResult() {
      return result_;
    }

    // optional string msgCode = 8;
    public static final int MSGCODE_FIELD_NUMBER = 8;
    private java.lang.Object msgCode_;
    /**
     * <code>optional string msgCode = 8;</code>
     */
    public boolean hasMsgCode() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string msgCode = 8;</code>
     */
    public java.lang.String getMsgCode() {
      java.lang.Object ref = msgCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgCode = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMsgCodeBytes() {
      java.lang.Object ref = msgCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string message = 9;
    public static final int MESSAGE_FIELD_NUMBER = 9;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 9;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string message = 9;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 9;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0L;
      version_ = "";
      service_ = "";
      sourceId_ = 0L;
      payloadData_ = com.google.protobuf.ByteString.EMPTY;
      payloadClass_ = "";
      result_ = com.mrmq.poker.common.proto.Rpc.RpcMessage.Result.SUCCESS;
      msgCode_ = "";
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasService()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getVersionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getServiceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, sourceId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, payloadData_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getPayloadClassBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(7, result_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getMsgCodeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getVersionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getServiceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, sourceId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, payloadData_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getPayloadClassBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, result_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getMsgCodeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mrmq.poker.common.proto.Rpc.RpcMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mrmq.poker.common.proto.Rpc.RpcMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.Rpc.RpcMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mrmq.poker.common.proto.Rpc.RpcMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.Rpc.RpcMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mrmq.poker.common.proto.Rpc.RpcMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.Rpc.RpcMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mrmq.poker.common.proto.Rpc.RpcMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mrmq.poker.common.proto.Rpc.RpcMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mrmq.poker.common.proto.Rpc.RpcMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mrmq.poker.common.proto.Rpc.RpcMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RpcMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mrmq.poker.common.proto.Rpc.RpcMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mrmq.poker.common.proto.Rpc.internal_static_RpcMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mrmq.poker.common.proto.Rpc.internal_static_RpcMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mrmq.poker.common.proto.Rpc.RpcMessage.class, com.mrmq.poker.common.proto.Rpc.RpcMessage.Builder.class);
      }

      // Construct using com.mrmq.poker.common.proto.Rpc.RpcMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        service_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        sourceId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        payloadData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        payloadClass_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        result_ = com.mrmq.poker.common.proto.Rpc.RpcMessage.Result.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000040);
        msgCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mrmq.poker.common.proto.Rpc.internal_static_RpcMessage_descriptor;
      }

      public com.mrmq.poker.common.proto.Rpc.RpcMessage getDefaultInstanceForType() {
        return com.mrmq.poker.common.proto.Rpc.RpcMessage.getDefaultInstance();
      }

      public com.mrmq.poker.common.proto.Rpc.RpcMessage build() {
        com.mrmq.poker.common.proto.Rpc.RpcMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mrmq.poker.common.proto.Rpc.RpcMessage buildPartial() {
        com.mrmq.poker.common.proto.Rpc.RpcMessage result = new com.mrmq.poker.common.proto.Rpc.RpcMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.service_ = service_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sourceId_ = sourceId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.payloadData_ = payloadData_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.payloadClass_ = payloadClass_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.msgCode_ = msgCode_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mrmq.poker.common.proto.Rpc.RpcMessage) {
          return mergeFrom((com.mrmq.poker.common.proto.Rpc.RpcMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mrmq.poker.common.proto.Rpc.RpcMessage other) {
        if (other == com.mrmq.poker.common.proto.Rpc.RpcMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasVersion()) {
          bitField0_ |= 0x00000002;
          version_ = other.version_;
          onChanged();
        }
        if (other.hasService()) {
          bitField0_ |= 0x00000004;
          service_ = other.service_;
          onChanged();
        }
        if (other.hasSourceId()) {
          setSourceId(other.getSourceId());
        }
        if (other.hasPayloadData()) {
          setPayloadData(other.getPayloadData());
        }
        if (other.hasPayloadClass()) {
          bitField0_ |= 0x00000020;
          payloadClass_ = other.payloadClass_;
          onChanged();
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasMsgCode()) {
          bitField0_ |= 0x00000080;
          msgCode_ = other.msgCode_;
          onChanged();
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000100;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasService()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mrmq.poker.common.proto.Rpc.RpcMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mrmq.poker.common.proto.Rpc.RpcMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 id = 1;
      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // required string version = 2;
      private java.lang.Object version_ = "";
      /**
       * <code>required string version = 2;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string version = 2;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string version = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string version = 2;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string version = 2;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>required string version = 2;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        version_ = value;
        onChanged();
        return this;
      }

      // required string service = 3;
      private java.lang.Object service_ = "";
      /**
       * <code>required string service = 3;</code>
       */
      public boolean hasService() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string service = 3;</code>
       */
      public java.lang.String getService() {
        java.lang.Object ref = service_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          service_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string service = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServiceBytes() {
        java.lang.Object ref = service_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          service_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string service = 3;</code>
       */
      public Builder setService(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        service_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string service = 3;</code>
       */
      public Builder clearService() {
        bitField0_ = (bitField0_ & ~0x00000004);
        service_ = getDefaultInstance().getService();
        onChanged();
        return this;
      }
      /**
       * <code>required string service = 3;</code>
       */
      public Builder setServiceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        service_ = value;
        onChanged();
        return this;
      }

      // optional int64 source_id = 4;
      private long sourceId_ ;
      /**
       * <code>optional int64 source_id = 4;</code>
       */
      public boolean hasSourceId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 source_id = 4;</code>
       */
      public long getSourceId() {
        return sourceId_;
      }
      /**
       * <code>optional int64 source_id = 4;</code>
       */
      public Builder setSourceId(long value) {
        bitField0_ |= 0x00000008;
        sourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 source_id = 4;</code>
       */
      public Builder clearSourceId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sourceId_ = 0L;
        onChanged();
        return this;
      }

      // optional bytes payloadData = 5;
      private com.google.protobuf.ByteString payloadData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes payloadData = 5;</code>
       */
      public boolean hasPayloadData() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes payloadData = 5;</code>
       */
      public com.google.protobuf.ByteString getPayloadData() {
        return payloadData_;
      }
      /**
       * <code>optional bytes payloadData = 5;</code>
       */
      public Builder setPayloadData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        payloadData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes payloadData = 5;</code>
       */
      public Builder clearPayloadData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        payloadData_ = getDefaultInstance().getPayloadData();
        onChanged();
        return this;
      }

      // optional string payloadClass = 6;
      private java.lang.Object payloadClass_ = "";
      /**
       * <code>optional string payloadClass = 6;</code>
       */
      public boolean hasPayloadClass() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string payloadClass = 6;</code>
       */
      public java.lang.String getPayloadClass() {
        java.lang.Object ref = payloadClass_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          payloadClass_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string payloadClass = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPayloadClassBytes() {
        java.lang.Object ref = payloadClass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payloadClass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string payloadClass = 6;</code>
       */
      public Builder setPayloadClass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        payloadClass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string payloadClass = 6;</code>
       */
      public Builder clearPayloadClass() {
        bitField0_ = (bitField0_ & ~0x00000020);
        payloadClass_ = getDefaultInstance().getPayloadClass();
        onChanged();
        return this;
      }
      /**
       * <code>optional string payloadClass = 6;</code>
       */
      public Builder setPayloadClassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        payloadClass_ = value;
        onChanged();
        return this;
      }

      // optional .RpcMessage.Result result = 7;
      private com.mrmq.poker.common.proto.Rpc.RpcMessage.Result result_ = com.mrmq.poker.common.proto.Rpc.RpcMessage.Result.SUCCESS;
      /**
       * <code>optional .RpcMessage.Result result = 7;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .RpcMessage.Result result = 7;</code>
       */
      public com.mrmq.poker.common.proto.Rpc.RpcMessage.Result getResult() {
        return result_;
      }
      /**
       * <code>optional .RpcMessage.Result result = 7;</code>
       */
      public Builder setResult(com.mrmq.poker.common.proto.Rpc.RpcMessage.Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .RpcMessage.Result result = 7;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000040);
        result_ = com.mrmq.poker.common.proto.Rpc.RpcMessage.Result.SUCCESS;
        onChanged();
        return this;
      }

      // optional string msgCode = 8;
      private java.lang.Object msgCode_ = "";
      /**
       * <code>optional string msgCode = 8;</code>
       */
      public boolean hasMsgCode() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string msgCode = 8;</code>
       */
      public java.lang.String getMsgCode() {
        java.lang.Object ref = msgCode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msgCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgCode = 8;</code>
       */
      public com.google.protobuf.ByteString
          getMsgCodeBytes() {
        java.lang.Object ref = msgCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgCode = 8;</code>
       */
      public Builder setMsgCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        msgCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgCode = 8;</code>
       */
      public Builder clearMsgCode() {
        bitField0_ = (bitField0_ & ~0x00000080);
        msgCode_ = getDefaultInstance().getMsgCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgCode = 8;</code>
       */
      public Builder setMsgCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        msgCode_ = value;
        onChanged();
        return this;
      }

      // optional string message = 9;
      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 9;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string message = 9;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 9;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 9;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 9;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000100);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 9;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RpcMessage)
    }

    static {
      defaultInstance = new RpcMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RpcMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RpcMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RpcMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\"\371\002\n\nRpcMessage\022\n\n\002id\030\001 \002(\003\022\017" +
      "\n\007version\030\002 \002(\t\022\017\n\007service\030\003 \002(\t\022\021\n\tsour" +
      "ce_id\030\004 \001(\003\022\023\n\013payloadData\030\005 \001(\014\022\024\n\014payl" +
      "oadClass\030\006 \001(\t\022\"\n\006result\030\007 \001(\0162\022.RpcMess" +
      "age.Result\022\017\n\007msgCode\030\010 \001(\t\022\017\n\007message\030\t" +
      " \001(\t\"\270\001\n\006Result\022\013\n\007SUCCESS\020\000\022\010\n\004FAIL\020\001\022\023" +
      "\n\017INVALID_VERSION\020\002\022\023\n\017INVALID_SERVICE\020\003" +
      "\022\023\n\017INVALID_PAYLOAD\020\004\022\025\n\021NOT_AUTHENTICAT" +
      "ED\020\005\022\027\n\023SERVICE_UNAVAILABLE\020\006\022\024\n\020SERVICE" +
      "_MAINTAIN\020\010\022\022\n\016INTERNAL_ERROR\020cB\"\n\033com.m",
      "rmq.poker.common.protoB\003Rpc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RpcMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RpcMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RpcMessage_descriptor,
              new java.lang.String[] { "Id", "Version", "Service", "SourceId", "PayloadData", "PayloadClass", "Result", "MsgCode", "Message", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
