package com.mrmq.poker.db.entity;

// default package
// Generated Oct 2, 2015 12:16:55 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * PkCashflow generated by hbm2java
 */
public class PkCashflow implements java.io.Serializable {
	public enum PkCashflowStatus {
		INACTIVE(0),
		ACTIVE(1),
		LOCKED(2);
		
		private int value = 0;
		
		PkCashflowStatus(int value) {
			this.value = value;
		}
		
		public int getNumber() {
			return value;
		}
	}
	
	public enum PkCashflowType {
		DEPOSIT(1),
		WITHDRAW(2),
		BET(3),
		WIN(4),
		TAX(5);
		
		private int value = 0;
		
		PkCashflowType(int value) {
			this.value = value;
		}
		
		public int getNumber() {
			return value;
		}
	}
	
	public enum PkCashflowSourceType {
		GAME(1),
		CARD(2),
		CASH(3),
		BANK(4),
		GIFT(5),
		STORE(6),
		OTHER(9);
		
		private int value = 0;
		
		PkCashflowSourceType(int value) {
			this.value = value;
		}
		
		public int getNumber() {
			return value;
		}
	}
	
	private static final long serialVersionUID = 1L;
	private int cashflowId;
	private int userId;
	private int type;
	private BigDecimal amount;
	private BigDecimal promo;
	private BigDecimal cashBalance;
	private BigDecimal preBalance;
	private String currency;
	private BigDecimal taxes;
	private Integer source;
	private Integer sourceType;
	private Integer promoSource;
	private String billSeri;
	private String billNumber;
	private String billType;
	private int status;
	private Date inputDate;
	private Date updateDate;

	public PkCashflow() {
	}

	public PkCashflow(int cashflowId, int userId, int type, BigDecimal amount, BigDecimal cashBalance,
			BigDecimal preBalance, String currency, BigDecimal taxes, int status, Date inputDate, Date updateDate) {
		this.cashflowId = cashflowId;
		this.userId = userId;
		this.type = type;
		this.amount = amount;
		this.cashBalance = cashBalance;
		this.preBalance = preBalance;
		this.currency = currency;
		this.taxes = taxes;
		this.status = status;
		this.inputDate = inputDate;
		this.updateDate = updateDate;
	}

	public PkCashflow(int cashflowId, int userId, int type, BigDecimal amount, BigDecimal cashBalance,
			BigDecimal preBalance, String currency, BigDecimal taxes, Integer source, Integer sourceType, int status, Date inputDate,
			Date updateDate) {
		this.cashflowId = cashflowId;
		this.userId = userId;
		this.type = type;
		this.amount = amount;
		this.cashBalance = cashBalance;
		this.preBalance = preBalance;
		this.currency = currency;
		this.taxes = taxes;
		this.source = source;
		this.status = status;
		this.inputDate = inputDate;
		this.updateDate = updateDate;
		this.sourceType = sourceType;
	}

	public int getCashflowId() {
		return this.cashflowId;
	}

	public void setCashflowId(int cashflowId) {
		this.cashflowId = cashflowId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getCashBalance() {
		return this.cashBalance;
	}

	public void setCashBalance(BigDecimal cashBalance) {
		this.cashBalance = cashBalance;
	}

	public BigDecimal getPreBalance() {
		return this.preBalance;
	}

	public void setPreBalance(BigDecimal preBalance) {
		this.preBalance = preBalance;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public BigDecimal getTaxes() {
		return this.taxes;
	}

	public void setTaxes(BigDecimal taxes) {
		this.taxes = taxes;
	}

	public Integer getSource() {
		return this.source;
	}

	public void setSource(Integer source) {
		this.source = source;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getSourceType() {
		return sourceType;
	}

	public void setSourceType(Integer sourceType) {
		this.sourceType = sourceType;
	}

	public BigDecimal getPromo() {
		return promo;
	}

	public void setPromo(BigDecimal promo) {
		this.promo = promo;
	}

	public String getBillSeri() {
		return billSeri;
	}

	public void setBillSeri(String billSeri) {
		this.billSeri = billSeri;
	}

	public String getBillNumber() {
		return billNumber;
	}

	public void setBillNumber(String billNumber) {
		this.billNumber = billNumber;
	}

	public String getBillType() {
		return billType;
	}

	public void setBillType(String billType) {
		this.billType = billType;
	}

	public Integer getPromoSource() {
		return promoSource;
	}

	public void setPromoSource(Integer promoSource) {
		this.promoSource = promoSource;
	}

	@Override
	public String toString() {
		return "PkCashflow [cashflowId=" + cashflowId + ", userId=" + userId + ", type=" + type + ", amount=" + amount
				+ ", promo=" + promo + ", cashBalance=" + cashBalance + ", preBalance=" + preBalance + ", currency="
				+ currency + ", taxes=" + taxes + ", source=" + source + ", sourceType=" + sourceType + ", promoSource="
				+ promoSource + ", billSeri=" + billSeri + ", billNumber=" + billNumber + ", billType=" + billType
				+ ", status=" + status + ", inputDate=" + inputDate + ", updateDate=" + updateDate + "]";
	}
}
