package com.mrmq.poker.db.entity;
// Generated Oct 7, 2015 11:00:33 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * PkGame generated by hbm2java
 */
public class PkGame implements java.io.Serializable {
	public enum PkGameStatus {
		INACTIVE(0),
		ACTIVE(1),
		LOCKED(2);
		
		private int value = 0;
		
		PkGameStatus(int value) {
			this.value = value;
		}
		
		public int getNumber() {
			return value;
		}
	}
	
	public enum PkGameType {
		POKER("POKER");
		
		private String value;
		
		PkGameType(String value) {
			this.value = value;
		}
		
		public String getValue() {
			return value;
		}
	}
	
	private static final long serialVersionUID = 2800426247400456613L;
	private String gameId;
	private String gameName;
	private String gameType;
	private int minPlayer;
	private int maxPlayer;
	private int maxViewer;
	private BigDecimal smallBlind;
	private BigDecimal bigBlind;
	private BigDecimal minBet;
	private BigDecimal maxBet;
	private int timePerturn;
	private int timePergame;
	private String currency;
	private String comment;
	private int status;
	private Date createDate;
	private Date updateDate;

	public PkGame() {
	}

	public PkGame(String gameId, String gameName, String gameType, int minPlayer, int maxPlayer, int maxViewer,
			BigDecimal smallBlind, BigDecimal bigBlind, BigDecimal minBet, BigDecimal maxBet, int timePerturn,
			int timePergame, String currency, int status, Date createDate, Date updateDate) {
		this.gameId = gameId;
		this.gameName = gameName;
		this.gameType = gameType;
		this.minPlayer = minPlayer;
		this.maxPlayer = maxPlayer;
		this.maxViewer = maxViewer;
		this.smallBlind = smallBlind;
		this.bigBlind = bigBlind;
		this.minBet = minBet;
		this.maxBet = maxBet;
		this.timePerturn = timePerturn;
		this.timePergame = timePergame;
		this.currency = currency;
		this.status = status;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public PkGame(String gameId, String gameName, String gameType, int minPlayer, int maxPlayer, int maxViewer,
			BigDecimal smallBlind, BigDecimal bigBlind, BigDecimal minBet, BigDecimal maxBet, int timePerturn,
			int timePergame, String currency, String comment, int status, Date createDate, Date updateDate) {
		this.gameId = gameId;
		this.gameName = gameName;
		this.gameType = gameType;
		this.minPlayer = minPlayer;
		this.maxPlayer = maxPlayer;
		this.maxViewer = maxViewer;
		this.smallBlind = smallBlind;
		this.bigBlind = bigBlind;
		this.minBet = minBet;
		this.maxBet = maxBet;
		this.timePerturn = timePerturn;
		this.timePergame = timePergame;
		this.currency = currency;
		this.comment = comment;
		this.status = status;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public String getGameId() {
		return this.gameId;
	}

	public void setGameId(String gameId) {
		this.gameId = gameId;
	}

	public String getGameName() {
		return this.gameName;
	}

	public void setGameName(String gameName) {
		this.gameName = gameName;
	}

	public String getGameType() {
		return this.gameType;
	}

	public void setGameType(String gameType) {
		this.gameType = gameType;
	}

	public int getMinPlayer() {
		return this.minPlayer;
	}

	public void setMinPlayer(int minPlayer) {
		this.minPlayer = minPlayer;
	}

	public int getMaxPlayer() {
		return this.maxPlayer;
	}

	public void setMaxPlayer(int maxPlayer) {
		this.maxPlayer = maxPlayer;
	}

	public int getMaxViewer() {
		return this.maxViewer;
	}

	public void setMaxViewer(int maxViewer) {
		this.maxViewer = maxViewer;
	}

	public BigDecimal getSmallBlind() {
		return this.smallBlind;
	}

	public void setSmallBlind(BigDecimal smallBlind) {
		this.smallBlind = smallBlind;
	}

	public BigDecimal getBigBlind() {
		return this.bigBlind;
	}

	public void setBigBlind(BigDecimal bigBlind) {
		this.bigBlind = bigBlind;
	}

	public BigDecimal getMinBet() {
		return this.minBet;
	}

	public void setMinBet(BigDecimal minBet) {
		this.minBet = minBet;
	}

	public BigDecimal getMaxBet() {
		return this.maxBet;
	}

	public void setMaxBet(BigDecimal maxBet) {
		this.maxBet = maxBet;
	}

	public int getTimePerturn() {
		return this.timePerturn;
	}

	public void setTimePerturn(int timePerturn) {
		this.timePerturn = timePerturn;
	}

	public int getTimePergame() {
		return this.timePergame;
	}

	public void setTimePergame(int timePergame) {
		this.timePergame = timePergame;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getRuleKey() {
		return maxPlayer + "" + minBet;
	}

	@Override
	public String toString() {
		return "PkGame [gameId=" + gameId + ", gameName=" + gameName + ", gameType=" + gameType + ", minPlayer="
				+ minPlayer + ", maxPlayer=" + maxPlayer + ", maxViewer=" + maxViewer + ", smallBlind=" + smallBlind
				+ ", bigBlind=" + bigBlind + ", minBet=" + minBet + ", maxBet=" + maxBet + ", timePerturn="
				+ timePerturn + ", timePergame=" + timePergame + ", currency=" + currency + ", comment=" + comment
				+ ", status=" + status + ", createDate=" + createDate + ", updateDate=" + updateDate + "]";
	}
	
}
