package com.mrmq.poker.db.entity;
// Generated Oct 2, 2015 12:16:55 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.beans.BeanUtils;

/**
 * PkUsers generated by hbm2java
 */
public class PkUser implements java.io.Serializable, Cloneable {
	public enum PkUserStatus {
		INACTIVE(0),
		ACTIVE(1),
		LOCKED(2),
		DEACTIVATE(9);
		
		private int value = 0;
		
		PkUserStatus(int value) {
			this.value = value;
		}
		
		public int getNumber() {
			return value;
		}
	}
	
	public enum PkUserGroup {
		DEMO("DEMO"),
		PUB("PUB"),
		FB("FB");
		
		private String value;
		
		PkUserGroup(String value) {
			this.value = value;
		}
		
		public String getValue() {
			return value;
		}
	}
	
	private static final long serialVersionUID = 1L;
	private Integer userId;
	private String login;
	private String pass;
	private String userGroup;
	private String userName;
	private String avataUrl;
	private String country;
	private String city;
	private String state;
	private String zipcode;
	private String address;
	private String phone;
	private String email;
	private BigDecimal balance;
	private BigDecimal prevBalance;
	private BigDecimal credit;
	private BigDecimal taxes;
	private String currency;
	private String pubKey;
	private int status;
	private String comment;
	private Date regDate;
	private Date updateDate;

	public PkUser() {
	}

	public PkUser(String login, String pass, String group, String name, BigDecimal balance, BigDecimal prevBalance,
			BigDecimal credit, BigDecimal taxes, String currency, int status, Date regDate, Date updateDate) {
		this.login = login;
		this.pass = pass;
		this.userGroup = group;
		this.userName = name;
		this.balance = balance;
		this.prevBalance = prevBalance;
		this.credit = credit;
		this.taxes = taxes;
		this.currency = currency;
		this.status = status;
		this.regDate = regDate;
		this.updateDate = updateDate;
	}

	public PkUser(String login, String pass, String group, String name, String avata, String country, String city, String state,
			String zipcode, String address, String phone, String email, BigDecimal balance, BigDecimal prevBalance,
			BigDecimal credit, BigDecimal taxes, String currency, String pubKey, int status, String comment,
			Date regDate, Date updateDate) {
		this.login = login;
		this.pass = pass;
		this.userGroup = group;
		this.userName = name;
		this.avataUrl = avata;
		this.country = country;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.address = address;
		this.phone = phone;
		this.email = email;
		this.balance = balance;
		this.prevBalance = prevBalance;
		this.credit = credit;
		this.taxes = taxes;
		this.currency = currency;
		this.pubKey = pubKey;
		this.status = status;
		this.comment = comment;
		this.regDate = regDate;
		this.updateDate = updateDate;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public String getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(String group) {
		this.userGroup = group;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String name) {
		this.userName = name;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public BigDecimal getPrevBalance() {
		return this.prevBalance;
	}

	public void setPrevBalance(BigDecimal prevBalance) {
		this.prevBalance = prevBalance;
	}

	public BigDecimal getCredit() {
		return this.credit;
	}

	public void setCredit(BigDecimal credit) {
		this.credit = credit;
	}

	public BigDecimal getTaxes() {
		return this.taxes;
	}

	public void setTaxes(BigDecimal taxes) {
		this.taxes = taxes;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getPubKey() {
		return this.pubKey;
	}

	public void setPubKey(String pubKey) {
		this.pubKey = pubKey;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * Clone to new Object
	 * */
	public PkUser clone() {
		PkUser cloned = new PkUser();
		
		BeanUtils.copyProperties(this, cloned);
		
		return cloned;
	}
	
	public String getAvataUrl() {
		return avataUrl;
	}

	public void setAvataUrl(String avataUrl) {
		this.avataUrl = avataUrl;
	}

	@Override
	public String toString() {
		return "PkUser [userId=" + userId + ", login=" + login + ", pass="
				+ pass + ", userGroup=" + userGroup + ", userName=" + userName
				+ ", avataUrl=" + avataUrl + ", country=" + country + ", city="
				+ city + ", state=" + state + ", zipcode=" + zipcode
				+ ", address=" + address + ", phone=" + phone + ", email="
				+ email + ", balance=" + balance + ", prevBalance="
				+ prevBalance + ", credit=" + credit + ", taxes=" + taxes
				+ ", currency=" + currency + ", pubKey=" + pubKey + ", status="
				+ status + ", comment=" + comment + ", regDate=" + regDate
				+ ", updateDate=" + updateDate + "]";
	}

}
